name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: ".tests/findmaxnumber_test.py"
      id: tests-findmaxnumber-test-py
      uses: classroom-resources/autograding-python-grader@v1
      with:
        timeout: 10
        max-score: 5
        setup-command: ''
    - name: ".tests/mean_test.py"
      id: tests-mean-test-py
      uses: classroom-resources/autograding-python-grader@v1
      with:
        timeout: 10
        max-score: 5
        setup-command: ''
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        TESTS-FINDMAXNUMBER-TEST-PY_RESULTS: "${{steps.tests-findmaxnumber-test-py.outputs.result}}"
        TESTS-MEAN-TEST-PY_RESULTS: "${{steps.tests-mean-test-py.outputs.result}}"
      with:
        runners: tests-findmaxnumber-test-py, tests-mean-test-py
